Repository shinhancard/dev-portal, pull requests merged in 2023-08, with the labels that each got.

#68 code style init
  .vscode/settings.json
  CODE_STYLE.md
  yarn.lock
Labels: doc, environment

#70 Feature/eks pipeline
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yaml
  app-config.production.yaml
  app-config.yaml
  packages/backend/Dockerfile
  packages/backend/src/index.ts
  packages/backend/src/plugins/healthcheck.ts
Labels: enhancement, feature, dependencies

#78 Feature/software catalog example
  .gitignore
  README.md
  app-config.yaml
  packages/app/package.json
  packages/app/src/App.tsx
  packages/backend/package.json
  packages/backend/src/index.ts
  packages/backend/src/plugins/formData.ts
  packages/backend/src/providers/exampleRouter.ts
  storybook/yarn.lock
  yarn.lock
Labels: feature

#82 Feature/38 techdoc add
  .github/workflows/build.yaml
  README.md
  app-config.production.yaml
  app-config.yaml
  catalog-info.yaml
  packages/backend/Dockerfile
Labels: feature

#84 Feature/generate file by action
  .gitignore
  README.md
  app-config.yaml
  packages/app/package.json
  packages/app/src/components/catalog/EntityPage.tsx
  packages/backend/package.json
  packages/backend/src/index.ts
  packages/backend/src/plugins/catalog.ts
  packages/backend/src/plugins/formData.ts
  packages/backend/src/plugins/generate/dependency/dependcy.ts
  packages/backend/src/plugins/generate/dependency/gradle.ts
  packages/backend/src/plugins/generate/dependency/index.ts
  packages/backend/src/plugins/gitlab.ts
  packages/backend/src/plugins/scaffolder.ts
  packages/backend/src/providers/scaffolderRouter.ts
Labels: feature
